server:
  port: 8080

spring:
  application:
    name: ConvexHull Visualizer API

logging:
  level:
    root: INFO
    com.prolificdev.convexhullvisualizer: DEBUG  # dein Package mit Debug-Logs
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"